apiVersion: v1
kind: Pod
metadata:
  name: git-pod-puller
  labels:
    name: git-pod-puller
spec:
  containers:
  - name: git-pod-puller
    image: popcor255/git-pod-puller:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
